# Model Layers 之二
Model Layers第一部分的笔记在

anders-test/basics/04-buildmodel_tutorial.ipynb

的Model Layers部分，主要描述基本的神经网络的Layer组件

此部分主要描述rnn用到的Layer组件

In [2]:
# 导入程序所需要的程序包

#PyTorch用的包
import torch
import torch.nn as nn
import torch.optim

from collections import Counter #搜集器，可以让统计词频更简单

#绘图、计算用的程序包
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import rc
import numpy as np

# nn.Embedding

https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html?highlight=embedding#torch.nn.Embedding

下面这篇文章讲了用法，看得不是特别懂

https://blog.csdn.net/qq_41477675/article/details/114645012

In [9]:
# an Embedding module containing 10 tensors of size 3
embedding = nn.Embedding(10, 3)
# weight存储了20条数据，每条数据是size=3的数组
print(embedding.weight)

Parameter containing:
tensor([[-0.2075,  1.2400, -1.4663],
        [-1.4736, -0.7501, -1.5635],
        [-0.1566,  0.0823, -0.5093],
        [-0.1393,  0.2986,  0.9383],
        [-0.6688, -0.8318, -0.1951],
        [ 0.7724,  0.4891, -1.2531],
        [ 0.4961, -0.3942,  1.3848],
        [ 0.7122, -0.7672, -0.4191],
        [ 0.2549,  1.4342,  0.0022],
        [-1.7566, -1.2855,  0.9330]], requires_grad=True)


In [14]:
# a batch of 2 samples of 4 indices each
input = torch.LongTensor([[1, 2, 4, 5], [4, 3, 2, 9]])
out = embedding(input)
# 将索引变为weight对应的数组
print(out)

tensor([[[-1.4736, -0.7501, -1.5635],
         [-0.1566,  0.0823, -0.5093],
         [-0.6688, -0.8318, -0.1951],
         [ 0.7724,  0.4891, -1.2531]],

        [[-0.6688, -0.8318, -0.1951],
         [-0.1393,  0.2986,  0.9383],
         [-0.1566,  0.0823, -0.5093],
         [-1.7566, -1.2855,  0.9330]]], grad_fn=<EmbeddingBackward0>)


In [17]:
# 1维的可以
input = torch.LongTensor([1, 2, 4, 5])
out = embedding(input)
print(out)

tensor([[-1.4736, -0.7501, -1.5635],
        [-0.1566,  0.0823, -0.5093],
        [-0.6688, -0.8318, -0.1951],
        [ 0.7724,  0.4891, -1.2531]], grad_fn=<EmbeddingBackward0>)


In [16]:
# 3维的也可以
input = torch.LongTensor([[[1, 2], [4, 5]], [[4, 3], [2, 9]]])
out = embedding(input)
# 将索引变为weight对应的数组
print(out)

tensor([[[[-1.4736, -0.7501, -1.5635],
          [-0.1566,  0.0823, -0.5093]],

         [[-0.6688, -0.8318, -0.1951],
          [ 0.7724,  0.4891, -1.2531]]],


        [[[-0.6688, -0.8318, -0.1951],
          [-0.1393,  0.2986,  0.9383]],

         [[-0.1566,  0.0823, -0.5093],
          [-1.7566, -1.2855,  0.9330]]]], grad_fn=<EmbeddingBackward0>)


# nn.RNN
https://pytorch.org/docs/stable/generated/torch.nn.RNN.html


In [29]:
# 看不懂，只是字面上的一些猜测
# 1.input size = 10, hidden size = 20 ,layers = 2
#   输入数据的节点数为10，类似神经网络的输入，两个隐含层，每个隐含层20个节点，那输出层节点数量怎么没有定义？
rnn = nn.RNN(10, 20, 2)
input = torch.randn(5, 10)
print(input)

tensor([[-4.9338e-01,  3.7022e-03,  1.3726e+00,  8.7226e-01, -1.6057e+00,
          1.2904e+00,  6.2513e-01,  5.4893e-01,  7.7695e-01,  5.5325e-01],
        [ 1.6297e-01, -5.5922e-01,  5.6360e-01, -5.1773e-01,  1.1935e+00,
         -2.8345e-01,  2.2670e+00,  7.4588e-01,  2.0257e+00,  6.9097e-01],
        [-1.4368e+00, -1.3536e+00, -1.0331e+00,  1.7335e-01,  2.6637e-01,
         -9.0333e-01, -4.0994e-01, -5.8604e-01,  8.2222e-01, -7.6230e-01],
        [-1.6917e+00,  4.6187e-01,  4.1468e+00,  1.2293e+00,  1.4621e+00,
         -6.3196e-01,  9.2742e-01,  8.2235e-01, -5.6722e-01,  4.7417e-01],
        [-1.3807e+00,  9.1801e-01, -8.1305e-01,  1.8950e-01, -3.6900e-01,
          4.1568e-02, -1.6230e+00,  1.6472e+00,  1.3082e+00, -1.8331e+00]])


In [41]:
# 我猜的：这是隐含层的数据，必须是两个隐含层，每个隐含层20个节点，和上面rnn的定义是对应的
h0 = torch.randn(2, 20)
output, hn = rnn(input, h0)
# 输出的数据节点数，变成了隐含层的数量
print(output.shape)

torch.Size([5, 20])


In [42]:
# 输出的隐含层shape没有变，但是数据变了
print(hn.shape)
print(h0)
print(hn)

torch.Size([2, 20])
tensor([[-0.2443, -1.1628, -1.1109, -0.9333, -0.2296, -0.5836,  0.4364,  0.8991,
          0.1694,  0.3182, -1.4104,  0.0568,  0.2098, -0.5805, -0.0537,  1.0404,
         -0.0365,  0.5585,  1.1958, -1.4516],
        [ 0.4240,  1.1509,  0.6385, -0.7588, -0.7377,  0.0036, -0.3537,  0.4396,
         -1.0393,  0.5925,  1.3591, -0.6779,  1.4081,  0.6752,  0.1576,  0.0372,
          1.7420, -0.9438, -0.8772,  0.2320]])
tensor([[ 0.2007,  0.6427, -0.6075,  0.2654,  0.5296,  0.1560, -0.0102,  0.3019,
         -0.2374,  0.6755,  0.0437,  0.1511,  0.3099,  0.7050, -0.1627, -0.2532,
          0.6013,  0.4019, -0.6291, -0.4952],
        [ 0.0724, -0.1898,  0.2909,  0.1954, -0.3370, -0.0911, -0.5759, -0.0946,
         -0.2182, -0.7548,  0.1710,  0.8660, -0.3704, -0.2506,  0.1434, -0.2550,
         -0.3803,  0.1574, -0.0298, -0.3461]], grad_fn=<SqueezeBackward1>)


In [48]:
# 官网的例子
# input size = 10, hidden size = 20 ,layers = 2
rnn = nn.RNN(10, 20, 2)
# 5条数据，10个节点，3是啥？
input = torch.randn(5, 3, 10)
# 2个隐含层，每个隐含层20个节点，3是啥？要跟上面的那个3对应
h0 = torch.randn(2, 3, 20)
output, hn = rnn(input, h0)
print(output.shape)
print(hn.shape)

torch.Size([5, 3, 20])
torch.Size([2, 3, 20])


# nn.InstanceNorm2d
https://pytorch.org/docs/stable/generated/torch.nn.InstanceNorm2d.html?highlight=instancenorm2d#torch.nn.InstanceNorm2d

看不懂，下面的例子我也看不懂

In [3]:
# Without Learnable Parameters
m = nn.InstanceNorm2d(100)
# With Learnable Parameters
m = nn.InstanceNorm2d(100, affine=True)
input = torch.randn(20, 100, 35, 45)
output = m(input)
print(output.shape)

torch.Size([20, 100, 35, 45])


# F.relu
只是将负值变为0，所以shape不变
        

# F.LeakyReLU
https://pytorch.org/docs/stable/generated/torch.nn.LeakyReLU.html

应该和F.relu类似吧